NUM_OF_FLOORS = 10
NUM_OF_ELEVATORS = 3
#visiblity
HEIGHT_SCREEN_COMP = 620
HEIGHT_FLOOR = 50
BUILDING_WIDTH = 50
dim_y = HEIGHT_FLOOR*NUM_OF_FLOORS
if dim_y > HEIGHT_SCREEN_COMP:
    HEIGHT_FLOOR = int(HEIGHT_SCREEN_COMP/NUM_OF_FLOORS)
HEIGHT_BLACK_LINE = int(HEIGHT_FLOOR/7)
ELEVATOR_WIDTH = HEIGHT_FLOOR
WINDOW_SIZE = (BUILDING_WIDTH+(NUM_OF_ELEVATORS * ELEVATOR_WIDTH), NUM_OF_FLOORS*HEIGHT_FLOOR)
FONT_SIZE_BUTTON = int(HEIGHT_FLOOR/3)
FONT_SIZE_TIMER = int(FONT_SIZE_BUTTON/2)

BUTTON_COLOR = (170,170,170)

#movment
SPEED = 2*HEIGHT_FLOOR
DELEAY_TIME = 2

#paths
SOUND_PATH = r"assets/ding.mp3"
ELEVATOR_PIC = r"assets/elv.png"
IMG_BUILDING_PATH = r"assets/BUILDING.JPG"


#colors
WHITE = (255,255,255)
BLACK = (0,0,0)
RED = (255,0,0)
GREEN = (0,255,0)


def ind_min(list):
    """"
    return (index(min),min)
    """
    return min(enumerate(list),key  = lambda x : x[1])
